"""initial schema

Revision ID: 4f5285ebdae8
Revises: 
Create Date: 2026-05-24 10:53:00.261272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5285ebdae8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=True),
    sa.Column('region', sa.String(length=60), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('languages_json', sa.JSON(), nullable=True),
    sa.Column('nomad_visa_available', sa.Boolean(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=False)
    op.create_index(op.f('ix_countries_nomad_visa_available'), 'countries', ['nomad_visa_available'], unique=False)
    op.create_index(op.f('ix_countries_region'), 'countries', ['region'], unique=False)
    op.create_index(op.f('ix_countries_slug'), 'countries', ['slug'], unique=True)
    op.create_table('distribution_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_code', sa.Integer(), nullable=True),
    sa.Column('response_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_distribution_logs_channel'), 'distribution_logs', ['channel'], unique=False)
    op.create_index(op.f('ix_distribution_logs_created_at'), 'distribution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_distribution_logs_success'), 'distribution_logs', ['success'], unique=False)
    op.create_index(op.f('ix_distribution_logs_url'), 'distribution_logs', ['url'], unique=False)
    op.create_table('keyword_opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword', sa.String(length=300), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('keyword_difficulty', sa.Float(), nullable=True),
    sa.Column('cpc_usd', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=40), nullable=True),
    sa.Column('serp_features_json', sa.JSON(), nullable=True),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_opportunities_discovered_at'), 'keyword_opportunities', ['discovered_at'], unique=False)
    op.create_index(op.f('ix_keyword_opportunities_keyword'), 'keyword_opportunities', ['keyword'], unique=False)
    op.create_index(op.f('ix_keyword_opportunities_opportunity_score'), 'keyword_opportunities', ['opportunity_score'], unique=False)
    op.create_table('scrape_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('google_news', 'visa_portal', 'safety_advisory', 'speedtest', 'cost_of_living', 'crypto_regulations', 'housing', 'coworking', 'nomad_forums', 'government_news', 'healthcare', name='source_type'), nullable=False),
    sa.Column('scrape_date', sa.Date(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('entries_found', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=40), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_slug'), 'topics', ['slug'], unique=True)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('nomad_score', sa.Float(), nullable=True),
    sa.Column('internet_avg_mbps', sa.Float(), nullable=True),
    sa.Column('cost_index', sa.Float(), nullable=True),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'slug', name='uq_country_city_slug')
    )
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=False)
    op.create_table('visa_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('visa_type', sa.String(length=120), nullable=False),
    sa.Column('visa_slug', sa.String(length=120), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('extendable', sa.Boolean(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('min_income_usd', sa.Float(), nullable=True),
    sa.Column('requirements_json', sa.JSON(), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('last_verified_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'visa_type', name='uq_visa_country_type')
    )
    op.create_index(op.f('ix_visa_info_country_id'), 'visa_info', ['country_id'], unique=False)
    op.create_index(op.f('ix_visa_info_last_verified_date'), 'visa_info', ['last_verified_date'], unique=False)
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_table', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('og_image_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('related_slugs_json', sa.JSON(), nullable=True),
    sa.Column('takeaways_json', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('reading_minutes', sa.Integer(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('canonical_source_url', sa.String(length=1000), nullable=True),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_table', 'source_id', name='uq_blog_source')
    )
    op.create_index(op.f('ix_blog_posts_city_id'), 'blog_posts', ['city_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_country_id'), 'blog_posts', ['country_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_created_at'), 'blog_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_blog_posts_published_date'), 'blog_posts', ['published_date'], unique=False)
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_blog_posts_source_id'), 'blog_posts', ['source_id'], unique=False)
    op.create_index(op.f('ix_blog_posts_source_table'), 'blog_posts', ['source_table'], unique=False)
    op.create_index(op.f('ix_blog_posts_topic_id'), 'blog_posts', ['topic_id'], unique=False)
    op.create_table('cost_breakdowns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('amount_usd', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('measured_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_breakdowns_category'), 'cost_breakdowns', ['category'], unique=False)
    op.create_index(op.f('ix_cost_breakdowns_city_id'), 'cost_breakdowns', ['city_id'], unique=False)
    op.create_index(op.f('ix_cost_breakdowns_measured_date'), 'cost_breakdowns', ['measured_date'], unique=False)
    op.create_index('ix_cost_city_cat_date', 'cost_breakdowns', ['city_id', 'category', 'measured_date'], unique=False)
    op.create_table('data_points',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('measured_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_points_city_id'), 'data_points', ['city_id'], unique=False)
    op.create_index(op.f('ix_data_points_country_id'), 'data_points', ['country_id'], unique=False)
    op.create_index(op.f('ix_data_points_measured_date'), 'data_points', ['measured_date'], unique=False)
    op.create_index(op.f('ix_data_points_metric'), 'data_points', ['metric'], unique=False)
    op.create_index(op.f('ix_data_points_topic_id'), 'data_points', ['topic_id'], unique=False)
    op.create_index('ix_dp_city_topic_date', 'data_points', ['city_id', 'topic_id', 'measured_date'], unique=False)
    op.create_index('ix_dp_country_topic_date', 'data_points', ['country_id', 'topic_id', 'measured_date'], unique=False)
    op.create_table('external_articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.Enum('google_news', 'visa_portal', 'safety_advisory', 'speedtest', 'cost_of_living', 'crypto_regulations', 'housing', 'coworking', 'nomad_forums', 'government_news', 'healthcare', name='source_type'), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('credibility', sa.Enum('official', 'tier1', 'tier2', 'community', name='credibility_tier'), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('published_date', sa.Date(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('article_type', sa.String(length=100), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('tone_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('analysis_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('scraped', 'analyzed', 'approved', 'sent', name='article_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_url', name='uq_ext_source_url')
    )
    op.create_index(op.f('ix_external_articles_city_id'), 'external_articles', ['city_id'], unique=False)
    op.create_index(op.f('ix_external_articles_country_id'), 'external_articles', ['country_id'], unique=False)
    op.create_index(op.f('ix_external_articles_published_date'), 'external_articles', ['published_date'], unique=False)
    op.create_index(op.f('ix_external_articles_source'), 'external_articles', ['source'], unique=False)
    op.create_index(op.f('ix_external_articles_topic_id'), 'external_articles', ['topic_id'], unique=False)
    op.create_table('internet_measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('download_mbps', sa.Float(), nullable=True),
    sa.Column('upload_mbps', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('jitter_ms', sa.Float(), nullable=True),
    sa.Column('measured_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_internet_city_date', 'internet_measurements', ['city_id', 'measured_date'], unique=False)
    op.create_index(op.f('ix_internet_measurements_city_id'), 'internet_measurements', ['city_id'], unique=False)
    op.create_index(op.f('ix_internet_measurements_measured_date'), 'internet_measurements', ['measured_date'], unique=False)
    op.create_table('landing_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_key', sa.String(length=160), nullable=False),
    sa.Column('page_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('sections_json', sa.JSON(), nullable=True),
    sa.Column('faq_json', sa.JSON(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('canonical_path', sa.String(length=240), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('llm_input_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_output_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_pages_city_id'), 'landing_pages', ['city_id'], unique=False)
    op.create_index(op.f('ix_landing_pages_country_id'), 'landing_pages', ['country_id'], unique=False)
    op.create_index(op.f('ix_landing_pages_last_generated_at'), 'landing_pages', ['last_generated_at'], unique=False)
    op.create_index(op.f('ix_landing_pages_page_key'), 'landing_pages', ['page_key'], unique=True)
    op.create_index(op.f('ix_landing_pages_page_type'), 'landing_pages', ['page_type'], unique=False)
    op.create_index(op.f('ix_landing_pages_topic_id'), 'landing_pages', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_pages_topic_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_page_type'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_page_key'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_last_generated_at'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_country_id'), table_name='landing_pages')
    op.drop_index(op.f('ix_landing_pages_city_id'), table_name='landing_pages')
    op.drop_table('landing_pages')
    op.drop_index(op.f('ix_internet_measurements_measured_date'), table_name='internet_measurements')
    op.drop_index(op.f('ix_internet_measurements_city_id'), table_name='internet_measurements')
    op.drop_index('ix_internet_city_date', table_name='internet_measurements')
    op.drop_table('internet_measurements')
    op.drop_index(op.f('ix_external_articles_topic_id'), table_name='external_articles')
    op.drop_index(op.f('ix_external_articles_source'), table_name='external_articles')
    op.drop_index(op.f('ix_external_articles_published_date'), table_name='external_articles')
    op.drop_index(op.f('ix_external_articles_country_id'), table_name='external_articles')
    op.drop_index(op.f('ix_external_articles_city_id'), table_name='external_articles')
    op.drop_table('external_articles')
    op.drop_index('ix_dp_country_topic_date', table_name='data_points')
    op.drop_index('ix_dp_city_topic_date', table_name='data_points')
    op.drop_index(op.f('ix_data_points_topic_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_metric'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_measured_date'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_country_id'), table_name='data_points')
    op.drop_index(op.f('ix_data_points_city_id'), table_name='data_points')
    op.drop_table('data_points')
    op.drop_index('ix_cost_city_cat_date', table_name='cost_breakdowns')
    op.drop_index(op.f('ix_cost_breakdowns_measured_date'), table_name='cost_breakdowns')
    op.drop_index(op.f('ix_cost_breakdowns_city_id'), table_name='cost_breakdowns')
    op.drop_index(op.f('ix_cost_breakdowns_category'), table_name='cost_breakdowns')
    op.drop_table('cost_breakdowns')
    op.drop_index(op.f('ix_blog_posts_topic_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_source_table'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_source_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_published_date'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_created_at'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_country_id'), table_name='blog_posts')
    op.drop_index(op.f('ix_blog_posts_city_id'), table_name='blog_posts')
    op.drop_table('blog_posts')
    op.drop_index(op.f('ix_visa_info_last_verified_date'), table_name='visa_info')
    op.drop_index(op.f('ix_visa_info_country_id'), table_name='visa_info')
    op.drop_table('visa_info')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_topics_slug'), table_name='topics')
    op.drop_table('topics')
    op.drop_table('scrape_logs')
    op.drop_index(op.f('ix_keyword_opportunities_opportunity_score'), table_name='keyword_opportunities')
    op.drop_index(op.f('ix_keyword_opportunities_keyword'), table_name='keyword_opportunities')
    op.drop_index(op.f('ix_keyword_opportunities_discovered_at'), table_name='keyword_opportunities')
    op.drop_table('keyword_opportunities')
    op.drop_index(op.f('ix_distribution_logs_url'), table_name='distribution_logs')
    op.drop_index(op.f('ix_distribution_logs_success'), table_name='distribution_logs')
    op.drop_index(op.f('ix_distribution_logs_created_at'), table_name='distribution_logs')
    op.drop_index(op.f('ix_distribution_logs_channel'), table_name='distribution_logs')
    op.drop_table('distribution_logs')
    op.drop_index(op.f('ix_countries_slug'), table_name='countries')
    op.drop_index(op.f('ix_countries_region'), table_name='countries')
    op.drop_index(op.f('ix_countries_nomad_visa_available'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
